{{- if .Values.configMaps}}
{{- range $name, $value := .Values.configMaps }}
{{- if $value.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- with $value.data }}
  {{- toYaml . | nindent 2}}
  {{- end }}
{{- end }}
{{- end }}
{{ end -}}
