{{- $root := . }}
{{- range $name, $value := .Values.randomSecret }}

---
{{- $secret := (lookup "v1" "Secret" $root.Release.Namespace $name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
data:
{{- range $value }}

{{- if $secret }}
  {{- $password_b64 := index $secret.data . }}
  {{- if $password_b64 }}
  {{ . }}: {{ $password_b64 }}
  {{- else }}
  {{- $password := randAlphaNum 20 }}
  {{ . }}: {{ $password | b64enc }}
  {{- end}}
{{- else}}
  {{- $password := randAlphaNum 32 }} 
  {{ . }}: {{ $password | b64enc }}
{{- end }}

#end range $value
{{- end }}
#end range
{{- end }}
