{{- $root := . }}
{{- range _, $value := .Values.envSecrets }}
{{- if $value.random -}}

---
{{- $secret := (lookup "v1" "Secret" $root.Release.Namespace $value.secretName) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.secretName }}
type: Opaque
data:
{{- if $secret }}
  {{- $password_b64 := index $secret.data $value.key }}
  {{ $value.key }}: {{ $password_b64 }}
{{- else}}
  {{- $password := randAlphaNum 32 }}
  {{ $value.key }}: {{ $password | b64enc }}
{{- end }}
# end if random
{{- end }}
#end range
{{- end }}
