{{- $root := . }}
{{- range $name, $value := .Values.sealedSecret }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
spec:
  template:
    metadata:
      name: {{ $name }}
      namespace: {{ $root.Release.namespace }}
  encryptedData:
    {{- with $value.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
      
# end range
{{- end }}
