{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eo-base-helm-chart.fullname" . }}
  labels:
    {{- include "eo-base-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.proxy }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eo-base-helm-chart.selectorLabels" . | nindent 4 }}
    component: {{ .Values.service.deployment }}
  {{- end }}
{{- if .Values.service.proxy }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "eo-base-helm-chart.fullname" . }}
  labels:
    {{- include "eo-base-helm-chart.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.service.proxy.host }}
    ports:
      - port: {{ .Values.service.port }}
        protocol: TCP
        name: http
{{- end }}
{{- end }}
