{{- if Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ett-base-helm-chart.fullname" . }}
  labels:
    {{- include "ett-base-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ett-base-helm-chart.selectorLabels" . | nindent 4 }}
    component: {{ .Values.service.deployment }}
{{- end }}
