name: Build and release helm chart

on:
  push:
    branches: [ main ]


jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release helm chart
        uses: Energinet-DataHub/.github/.github/actions/helm-release-chart@5.0.0
        with:
          dispatch_token: ${{ secrets.ACCESS_TOKEN }}
          chart_folder: chart
          chart_repository: Energinet-DataHub/helm-charts
          chart_version: v0.5.1
