name: Build and release helm chart

on:
  push:
    branches: [ main ]

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Energinet-DataHub/.github/.github/actions/helm-release-chart@helm_releases_action
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          chart_folder: chart
          chart_repository: Energinet-DataHub/helm-charts
