name: Test that the chart can lint

on: pull_request

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Helm lint
        run: helm lint chart

      - name: Helm lint with test values
        run: helm lint chart --values test/values.yaml
