name: Build and release helm chart

on:
  push:
    branches: [ main ]

jobs:
  helm_check_version:
    name: Helm chart check version
    uses: Energinet-DataHub/.github/.github/workflows/version-increment-check.yaml@main
    with:
      yaml_file: chart/Chart.yaml
      yaml_path: version

  helm-release:
    needs: [helm_check_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get chart version
        id: get_semver
        uses: Energinet-DataHub/.github/.github/actions/get-semver@main
        with:
          yaml_file: chart/Chart.yaml
          yaml_path: version

      - name: Release helm chart
        uses: Energinet-DataHub/.github/.github/actions/helm-release-chart@5.0.0
        with:
          dispatch_token: ${{ secrets.ACCESS_TOKEN }}
          release_token: ${{ secrets.ACCESS_TOKEN }}
          chart_folder: chart
          chart_repository: RasmusGodske/helm-charts
          chart_version: ${{ steps.get_semver.outputs.semver }}
