name: Test the deployment of the base chart

on: pull_request

jobs:
  test-base-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Install Chart
        run: helm install base chart -f test/values.yaml --set testFramework=true
      - name: Create secret
        run: kubectl create secret generic test --from-literal=test-key=test-value
      - name: Helm test chart
        run: helm test base --logs
